# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Recipe.create(name: "Shepherd's Pie", ingredients: "2 tablespoons olive oil, 1 cup chopped yellow onion, 1 lb. 90% lean ground beef -or ground lamb, 2 teaspoons dried parsley leaves, 1 teaspoon dried rosemary leaves, 1 teaspoon dried thyme leaves, 1/2 teaspoon salt, 1/2 teaspoon ground black pepper, 1 tablespoon Worcestershire sauce, 2 garlic cloves -minced, 2 tablespoons all purpose flour, 2 tablespoons tomato paste, 1 cup beef broth, 1 cup frozen mixed peas & carrots, 1/2 cup frozen corn kernels 1 1/2 - 2 lb. russet potatoes -about 2 large potatoes peeled and cut into 1 inch cubes, 8 tablespoons unsalted butter -1 stick, 1/3 cup half & half, 1/2 teaspoon garlic powder, 1/2 teaspoon salt, 1/4 teaspoon ground black pepper, 1/4 cup parmesan cheese", directions: "Make the Meat Filling. Add the oil to a large skillet and place it over medium-high heat for 2 minutes. Add the onions. Cook 5 minutes, stirring occasionally. Add the ground beef (or ground lamb) to the skillet and break it apart with a wooden spoon. Add the parsley, rosemary, thyme, salt, and and pepper. Stir well. Cook for 6-8 minutes, until the meat is browned, stirring occasionally. Add the Worcestershire sauce and garlic. Stir to combine. Cook for 1 minute. Add the flour and tomato paste. Stir until well incorporated and no clumps of tomato paste remain. Add the broth, frozen peas and carrots, and frozen corn. Bring the liquid to a boil then reduce to simmer. Simmer for 5 minutes, stirring occasionally. Set the meat mixture aside. Preheat oven to 400 degrees F. Make the potato topping. Place the potatoes in a large pot. Cover the potatoes with water. Bring the water to a boil. Reduce to a simmer. Cook until potatoes are fork tender, 10-15 minutes. Drain the potatoes in a colander. Return the potatoes to the hot pot. Let the potatoes rest in the hot pot for 1 minute to evaporate any remaining liquid. Add butter, half & half, garlic powder, salt, and pepper. Mash the potatoes and stir until all the ingredients are mixed together. Add the parmesan cheese to the potatoes. Stir until well combined. Assemble the casserole. Pour the meat mixture into a 9x9 (or 7x11) inch baking dish. Spread it out into an even layer. Spoon the mashed potatoes on top of the meat. Carefully spread into an even layer. If the baking dish looks very full, place it on a rimmed baking sheet so that the filling doesn’t bubble over into your oven. Bake uncovered for 25-30 minutes.** Cool for 15 minutes before serving.", skill_level: 1, meal_type: "dinner", user_id: 1, country_of_origin_id: 1)
Recipe.create(name: "Duck Confit with Spicy Pickled Raisins", ingredients: "8 skin-on, bone-in duck legs, 4 garlic cloves, thinly sliced, 1 teaspoon freshly ground black pepper plus more freshly cracked, 2 tablespoons plus 1 teaspoon kosher salt, 9 sprigs thyme, divided, 6 dried chiles de árbol, crushed, or 1 ½ tsp. crushed red pepper flakes, divided, 1/2 cup white wine vinegar, 1/4 cup sugar
2 teaspoons brown mustard seeds, 1 sprig rosemary, 1.5 cups golden raisins", directions: "Step 1 - Using the tip of a knife or the sharp tines of a carving fork, prick duck leg skin all over. Rub with garlic (slices should stick to skin) and season with 1 tsp. ground pepper and 2 Tbsp. salt. Step 2 - Preheat oven to 250°. Arrange duck, skin side down, in a roasting pan or large Dutch oven and add 8 thyme sprigs, 4 chiles (or 1 tsp. red pepper flakes), and ½ cup water. Cover pan with foil or lid and cook until fat is rendered (don’t be surprised: there will be lots), about 2 hours. Turn duck skin side up and nestle it into rendered fat. Cover pan and continue to cook until meat is very tender and bones easily wiggle when pulled, 2–2½ hours longer. Step 3 - Meanwhile, bring vinegar, sugar, mustard seeds, rosemary sprig, remaining thyme sprig, 2 chiles (or ½ tsp. red pepper flakes), 1 tsp. salt, and 1 cup water to a boil in a medium saucepan. Reduce heat and simmer, stirring occasionally, until sugar is dissolved, about 3 minutes. Mix in raisins, remove from heat, and let cool at least 1 hour. Step 4 - Increase oven temperature to 400°. Remove duck from fat and place, skin side up, on a rimmed baking sheet; reserve fat for another use (it will keep 3 weeks in refrigerator or 3 months in freezer; reheat and strain before using). Season duck with cracked pepper and roast until skin is brown and crisp, 30–35 minutes. Serve duck with pickled raisins. Step 5 - Do Ahead: Raisins can be pickled 1 week ahead. Cover and chill; bring to room temperature before serving. Duck can be cooked 1 week ahead. Pack duck in fat in an airtight container and chill.", skill_level: 5, meal_type: "dinner", user_id: 5, country_of_origin_id: 2)
Recipe.create(name: "Instant No Yeast Naan", ingredients: "¼ cup (60 grams) plain unsweetened yogurt, 1 tablespoon (8 grams) baking powder, 1½ cups (355 milliliters) lukewarm water, divided, plus more as needed, 2 cups (240 grams) whole wheat flour, 2 cups (240 grams) all-purpose flour, plus more for rolling, ⅓ teaspoon baking soda, 1 teaspoon salt, ½ teaspoon nigella seeds (optional), 4 cloves garlic, very finely chopped (optional), 1 tablespoon (14 grams) unsalted butter", directions: "1. In a small bowl, combine the yogurt, baking powder, and ⅓ cup (80 milliliters) of the warm water and set aside for a minute or two. 2. In a large mixing bowl, combine the flours, baking soda, and salt. Add the yogurt mixture and the remaining water. Knead to make a semi-soft dough. If you need more water, add a little at a time. It should not be very sticky or very hard. Once everything comes together to form a smooth dough, place it in an oiled bowl, cover with a damp towel, and let rest for at least 10 minutes. 3. Knead it for a couple of minutes and let rest for another 2 minutes. 4. Place a nonstick or a cast-iron pan (which I prefer) over medium-high heat and get it really hot. Take a piece of dough the size of a tennis ball and roll it out on a lightly floured countertop to approximately 10 inches (25 cm). 5. Sprinkle with a few nigella seeds and some garlic, if desired, and roll again so it gets stuck to the dough and doesn’t fall off while cooking. 6. Put the naan on the hot griddle and let it cook for 30-40 seconds. When you see a few bubbles on top, turn the naan over and cook the other side, 2-3 minutes total. 7. Smear some butter on both sides and serve hot, or wrap in a cloth and keep warm until ready to serve.", skill_level: 1, meal_type: "snack", user_id: 2, country_of_origin_id: 5)
Recipe.create(name: "Pan con Tomate", ingredients: "2 large, ripe beefsteak tomatoes, Kosher salt, 1 loaf ciabatta, split in half horizontally lengthwise, cut crosswise into 1 1/2-inch slices, Extra-virgin olive oil, 2 medium cloves garlic, split in half, Flaky sea salt, such as Maldon or fleur de sel", directions: "1. Split tomatoes in half horizontally. Place a box grater into a large bowl. Rub the cut faces of the tomatoes over the large holes of the box grater, using the flattened palm of your hand to move the tomatoes back and forth. The flesh should be grated off, while the skin remains intact in your hand. Discard the skin and season the tomato pulp with kosher salt to taste. 2. Adjust rack to 4 inches below broiler and preheat broiler to high. Place bread, cut side up, on a cutting board and drizzle with olive oil. Season with kosher salt. Place bread, cut side up, on a rack set in a tray or directly on the broiler rack and broil until crisp and starting to char around the edges, 2 to 3 minutes. 3. Remove bread from oven and rub with the split garlic cloves. Spoon tomato mixture over bread. Drizzle with more extra-virgin olive oil and season with flaky sea salt. Serve immediately.", skill_level: 1, meal_type: "breakfast", user_id: 3, country_of_origin_id: 4)
Recipe.create(name: "Chèvre Tomate Avec Herbes de Provence", ingredients: "1 fresh, crusty baguette, 1 or 2 ripe tomatoes, sliced, 1/3 pound bloomy rind goat cheese, such as Bucheron,1/3 pound French-style ham, optional, 1/2 teaspoon herbes de Provence, 1 small handful of fresh arugula, optional, 2 tablespoons extra-virgin olive oil, optional", directions: "Slice the baguette in half lengthwise, almost all the way through, and open. Drizzle the top and bottom baguette halves with olive oil. Slice the tomato slices in half, so they are in half moons. Slice the goat cheese into thin rounds, then slice them in half into half moons. If using, layer arugula, then ham onto the bottom of the sandwich. Then add alternating slices of tomato and goat cheese along the length of the sandwich.
Sprinkle with herbes de Provence. Close the baguette, press, and divide into halves or thirds.", skill_level: 1, meal_type: "lunch", user_id: 2, country_of_origin_id: 2)
Recipe.create(name: "Saag Paneer", ingredients: "8 cups milk, ¼ cup fresh lemon juice, 6 Tbsp. ghee or canola oil, 4 cloves garlic, chopped, One 1-inch piece ginger, peeled and chopped, 1 serrano chile, stemmed and chopped, 6 cups finely chopped spinach, Kosher salt, 6 Tbsp. heavy cream, ½ tsp. garam masala, ¼ tsp. cayenne, Indian flatbread or rice, for serving",  directions: "1. Make the cheese: Line a colander with 8 layers of cheesecloth, draping it over the sides, and set in a sink. In a large, nonstick pot over medium-high heat, bring the milk to a full boil, stirring often with a wooden spoon to prevent it from scorching on the bottom. Stir in the lemon juice, then lower the heat to medium-low and cook without stirring just until large curds form, about 30 seconds. Remove from the heat and set aside, without disturbing for 2 minutes, then pour the milk mixture into the colander. Gather the corners of cheesecloth together and gently squeeze out some of the excess liquid. Tie the opposite corners of the cheesecloth together to make a sack, and hang it from a large kitchen spoon suspended over a deep bowl. Set aside at room temperature until the excess liquid has thoroughly drained from the cheese, about 1½ hours. Transfer the sack to a plate, untie the cheesecloth, and loosely drape the corners over the cheese. Place a large heavy pot on top of the cheese, then set aside at room temperature to compress for 30 minutes more. Remove the pot and unwrap the cheese. Cut into ½-inch-by-1-inch pieces. 2. In a 12-inch nonstick skillet, heat the ghee over medium. Working in batches, add the cheese and fry until golden brown, about 6 minutes. Using a slotted spoon, transfer the cheese to a plate and set aside; reserve the skillet with ghee. 3. Make the spinach: In a blender, combine the garlic, ginger, chile, and ¼ cup water; purée into a smooth paste. Return the skillet with ghee to the stove, and heat over medium-high. Add the ginger-garlic paste and cook, stirring, until fragrant, about 30 seconds. Add the spinach, salt to taste, and cook, stirring often, until the spinach wilts, about 1 minute. Reduce the heat to medium-low, cover, and cook, stirring often, until the spinach is very soft, about 15 minutes. Stir in the cream, garam masala, and cayenne. Add the cheese to the skillet, cover, and continue cooking until the liquid thickens and spinach is soft, about 15 minutes more. Serve with flatbread or rice.", skill_level: 3, meal_type: "lunch", user_id: 3, country_of_origin_id: 5)
Recipe.create(name: "Bread and Butter Pudding", ingredients: "Generous 1/3 cup butter, at room temperature, 12 slices medium white bread, generous 1/3 cup raisins, 1 1/3 cups cream, 1 1/3 cups milk, 4 eggs, scant 1/2 cup firmly packed superfine sugar, 1/2 teaspoon ground cinnamon.", directions: "1. Generously butter an ovenproof dish. Remove the crusts from the bread and using the remaining butter coat both sides, and then cut each slive into quarters to form triangles. 2. Arrange a single layer of the bread triangles, overlapping slightly in the bottom of the buttered dish. Scatter over some of the raisins, then place a second layer of the bread triangles on top and scatter over the remaining raisins. Press down gently with a fish slice or a spatula. 3. To make the custard, heat the cream and milk in a pan until it almost comes to the boil. Remove from the heat. Meanwhile, whisk together the eggs, sugar and ground cinnamon in a large heatproof bowl set over a pan of simmering water until thickened and the whisk leaves a trail in the mixture. Remove from the heat and beat in the cream and milk mixture until well combined. Pour two-thirds of the custard over the layered bread triangles and leave to stand for about 30 minutes or until the bread has soaked up all of the custard. 4. Preheat the oven to 150 F. Pour the remaining custard over the soaked bread and butter triangles and arrange the reamining bread triangles on top. Press down firmly with a fish slice so that the custard comes halfway up the bread triangles. Bake for 30-35 minutes until the custard is just set and the top is golden brown. 5. To serve, bring the bread and butter pudding straight to the table and have a jug of custard ready. ", skill_level: 1, meal_type: "dessert", user_id: 4, country_of_origin_id: 1)

User.create(username: "mwood", password: "password", skill_level: 2)
User.create(username: "acarter", password: "password", skill_level: 3)
User.create(username: "albus", password: "password", skill_level: 4)
User.create(username: "davidrose", password: "password", skill_level: 1)
User.create(username: "dot", password: "password", skill_level: 5)

CountryOfOrigin.create(country: "Ireland")
CountryOfOrigin.create(country: "France")
CountryOfOrigin.create(country: "Italy")
CountryOfOrigin.create(country: "Spain")
CountryOfOrigin.create(country: "India")